project_id = "ldbvqzyqcgdyylzbxdqw"

[functions.verify-guess]
verify_jwt = false

[functions.get-quiz-metadata]
verify_jwt = false

[functions.start-quiz-session]
verify_jwt = false

[functions.save-quiz-progress]
verify_jwt = false
